### ISSUE TITLE
Handle whitespaces in filenames (load_pdf.py)

### ISSUE THREAD

**Issue by SylvainDe** [fallen/mescomptes#2]
Everywhere, instead of having:

`cmd = "blabla {filepath}".format(filepath=filepath)`

We shoud have:

`cmd = "blabla '{filepath}'".format(filepath=filepath)`

To avoid the following error:

`on auto detect le compte
/bin/sh: 1: Syntax error: "(" unexpected
auto detection of account failed!`

I'll try to suggest a PR

**Comment by fallen** [comment]
Ah yes, thanks! :)
